# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

name: Standup Azure Controller
on:
  workflow_dispatch:
    inputs:
      controller_id:
          description: "the unique controller id"
          required: true
          default: t1
      azure_location:
          description: "azure location / region"
          required: true
          default: "westeurope"
      zone:
          description: "the availability zone"
          required: true
          default: "1"
      vm_admin_username: 
          description: "the vm admin username"
          required: true
          default: "controller"
      vm_admin_password:
          description: "the vm admin password"
          required: true
          default: "Controller-Solace-123"

jobs: 
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Print Inputs
        run: |
          echo "inputs=${{toJson(github.event.inputs)}}"
  create_vm:
    runs-on: ubuntu-18.04
    outputs:
      publicIpAddress: ${{steps.azure_deploy.outputs.publicIPAddress}}
      resourceGroupName: ${{steps.azure_deploy.outputs.resourceGroupName}}
    env:
      PROJECT_PREFIX: '${{github.event.inputs.controller_id}}-solace-ci-controller'
      AZURE_RESOURCE_GROUP: '${{github.event.inputs.controller_id}}-solace-ci-controller-rg'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: "TESTS: List Files after checkout"
        run: |
          pwd
          ls -a
          echo "GITHUB_SHA=$GITHUB_SHA"
          echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
          echo "github.token=${{ github.token }}"  
      - name: Azure Login
        # https://github.com/marketplace/actions/azure-login
        uses: azure/login@v1.1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: "TEST: List all resource groups in specified location"
        run: |
          az group list --query "[?location=='${{github.event.inputs.azure_location}}']"
      - name: Create Resource Group    
        run: |
          az group create \
            --name ${AZURE_RESOURCE_GROUP} \
            --location ${{github.event.inputs.azure_location}} \
            --tags project=${PROJECT_PREFIX} \
            --verbose
      - name: Run ARM Deploy
        id: azure_deploy
        # https://github.com/marketplace/actions/deploy-azure-resource-manager-arm-template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{env.AZURE_RESOURCE_GROUP}}
          template: ./azure/azure-deploy.json
          parameters: id=${{github.event.inputs.controller_id}} zone=${{github.event.inputs.zone}} vm_admin_username=${{github.event.inputs.vm_admin_username}} vm_admin_password=${{github.event.inputs.vm_admin_password}}
      - name: "TEST: show the deploy output"
        run: |
          echo "outputs:"
          echo "${{toJson(steps.azure_deploy.outputs)}}"
  bootstrap_vm:
      runs-on: ubuntu-18.04
      needs: create_vm
      env:
        VM_PUBLIC_IP_ADDRESS: ${{needs.create_vm.outputs.publicIpAddress}}
        VM_USER_NAME: ${{github.event.inputs.vm_admin_username}}   
        VM_PASSWORD: ${{github.event.inputs.vm_admin_password}}   
      steps:        
        - name: "TEST: show the create_vm output"          
          run: |
            echo "outputs from create_vm:"
            echo "publicIpAddress = ${VM_PUBLIC_IP_ADDRESS}"
            echo "resourceGroupName = ${{needs.create_vm.outputs.resourceGroupName}}"
        - name: "TEST: pwd via ssh"
          # https://github.com/marketplace/actions/run-ssh-command
          uses: garygrossgarten/github-action-ssh@release
          with:
            command: |
              pwd
              ls -la
              echo "we are in!"
            host: ${{env.VM_PUBLIC_IP_ADDRESS}}
            username: ${{env.VM_USER_NAME}}
            password: ${{env.VM_PASSWORD}}
        - name: Copy bootstrap script     
          # https://github.com/garygrossgarten/github-action-scp   
          uses: garygrossgarten/github-action-scp@release
          with:
            local: ./azure/bootstrap.sh
            remote: ~/bootstrap.sh
            host: ${{env.VM_PUBLIC_IP_ADDRESS}}
            username: ${{env.VM_USER_NAME}}
            password: ${{env.VM_PASSWORD}}
        - name: Execute bootstrap script
          uses: garygrossgarten/github-action-ssh@release
          with:
            command: ~/bootstrap.sh
            host: ${{env.VM_PUBLIC_IP_ADDRESS}}
            username: ${{env.VM_USER_NAME}}
            password: ${{env.VM_PASSWORD}}


###
# The End.