# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

name: Standup Azure Controller
on:
  workflow_dispatch:
    inputs:
      controller_id:
          description: "the unique controller id"
          required: true
          default: t1
jobs: 
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Print Payload
        run: |
          echo "controller_id=${{ github.event.inputs.controller_id }}"
          echo "inputs="${{toJson(github.event.inputs)}}


    # - AZURE LOGIN
    #     - https://github.com/marketplace/actions/azure-login


###
# The End.