# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

name: Standup Azure Controller
on:
  workflow_dispatch:
    inputs:
      controller_id:
          description: "unique controller id"
          required: true
          default: w1
      azure_location:
          description: "azure location / region"
          required: true
          default: "westeurope"
      zone:
          description: "azure availability zone"
          required: true
          default: "1"
      vm_admin_username:
          description: "vm admin username"
          required: true
          default: "controller"

env:
  PROJECT_PREFIX: '${{github.event.inputs.controller_id}}-solace-ci-controller'
  AZURE_RESOURCE_GROUP: '${{github.event.inputs.controller_id}}-solace-ci-controller-rg'
  AZURE_DEPLOY_ARM_TEMPLATE: ./azure/.workflows/azure-deploy.json
  BOOTSTRAP_SH: ./azure/.workflows/bootstrap.sh

jobs:
  create_vm:
    runs-on: ubuntu-18.04
    outputs:
      publicIpAddress: ${{steps.azure_deploy.outputs.publicIPAddress}}
      resourceGroupName: ${{steps.azure_deploy.outputs.resourceGroupName}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      # - name: "TESTS: List Files after checkout"
      #   run: |
      #     pwd
      #     ls -a
      #     echo "GITHUB_SHA=$GITHUB_SHA"
      #     echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
      #     echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
      #     echo "GITHUB_REF=$GITHUB_REF"
      #     echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
      #     echo "github.token=${{ github.token }}"

      - name: Azure Login
        # https://github.com/marketplace/actions/azure-login
        uses: azure/login@v1.1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Create Azure Resource Group
        run: |
          az group create \
            --name ${AZURE_RESOURCE_GROUP} \
            --location ${{github.event.inputs.azure_location}} \
            --tags project=${PROJECT_PREFIX} \
            --verbose
      
      - name: Run ARM Deploy
        id: azure_deploy
        # https://github.com/marketplace/actions/deploy-azure-resource-manager-arm-template
        uses: azure/arm-deploy@v1.0.1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
          template: ${{ env.AZURE_DEPLOY_ARM_TEMPLATE }}
          parameters: vm_admin_public_key="${{ secrets.CONTROLLER_VM_PUBLIC_KEY }}" id=${{ github.event.inputs.controller_id }} zone=${{ github.event.inputs.zone }} vm_admin_username=${{ github.event.inputs.vm_admin_username }}
      
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${SSH_KEY}" > ~/.ssh/controller_key
          chmod 600 ~/.ssh/controller_key
          cat >>~/.ssh/config <<END
          Host controller
            HostName ${SSH_HOST}
            User ${SSH_USER}
            IdentityFile ~/.ssh/controller_key
            StrictHostKeyChecking no
          END
          chmod 600 ~/.ssh/config
          # cat ~/.ssh/config
        env:
          SSH_USER: ${{ github.event.inputs.vm_admin_username }}
          SSH_KEY: ${{ secrets.CONTROLLER_VM_PRIVATE_KEY }}
          SSH_HOST: ${{ steps.azure_deploy.outputs.publicIPAddress }}

      - name: Copy bootstrap script
        # https://github.com/garygrossgarten/github-action-scp
        # no error handling: workflow will not fail on error
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ${{ env.BOOTSTRAP_SH }}
          remote: bootstrap.sh
          host: ${{ steps.azure_deploy.outputs.publicIPAddress }}
          username: ${{ github.event.inputs.vm_admin_username }}
          privateKey: ${{ secrets.CONTROLLER_VM_PRIVATE_KEY }}

      # - name: ZZ
      #   run: |
      #     ssh controller "ls -la && pwd"

      - name: Set Bootstrap to Executable
        run: |
          ssh controller "chmod u+x bootstrap.sh"

      - name: Run Bootstrap
        run: |
          ssh controller "./bootstrap.sh > ./bootstrap.sh.log"
      
      # - name: Show Job Outputs
      #   run: |
      #     echo "outputs:"
      #     echo "${{toJson(jobs.create_vm.outputs)}}"

      # - name: "Show azure deploy outputs"
      #   run: |
      #     echo "${{toJson(steps.azure_deploy.outputs)}}"

      - name: Controller - Get Release
        run: |
          ssh controller "\
              mkdir ~/release && \
              cd ~/release
          
          "

      # RELEASE_TAG="v0.0.1"
      # curl -L https://github.com/solace-iot-team/solace-ci-controller/archive/v0.0.1.zip --output release.v0.0.1.zip

      # curl https://github.com/solace-iot-team/solace-ci-controller/releases/tag/v0.0.1

      # ssh controller "mkdir ~/release && cd ~/release && curl --silent 'https://github.com/solace-iot-team/solace-ci-controller/releases/latest'"
      
      #   mkdir ~/release > /dev/null 2>&1
      #   cd ~/release
      #   curl --silent "https://github.com/solace-iot-team/solace-ci-controller/releases/latest"

        
      #   releaseDir="$scriptDir/release"
      #   releaseProject="solace-int-rdp-az-funcs"
      #   gitReleaseURL="https://api.github.com/repos/solace-iot-team/$releaseProject/releases"

      #   resp=$(curl \
      #       --silent \
      #       -H "Accept: application/vnd.github.v3+json" \
      #       "$gitReleaseURL/latest"
      #       )
      #       if [[ $? != 0 ]]; then echo " >>> ERR: get latest release info"; exit 1; fi


###
# The End.
