# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

name: Standup Azure Controller
on:
  workflow_dispatch:
    inputs:
      controller_id:
          description: "unique controller id"
          required: true
          default: t3
      azure_location:
          description: "azure location / region"
          required: true
          default: "westeurope"
      zone:
          description: "azure availability zone"
          required: true
          default: "1"
      vm_admin_username:
          description: "vm admin username"
          required: true
          default: "controller"
      azure_key_vault_name:
          description: "name of the azure key vault"
          required: true
          # default: "solace-ci-controller-kv"
          default: "sol-ci-ctrl-kv-3"
      vm_admin_public_key_secret_name:
          description: "public key name in key vault"
          required: true
          default: "vm-admin-public-key"
      vm_admin_private_key_secret_name:
          description: "private key name in key vault"
          required: true
          default: "vm-admin-private-key"

env:
  PROJECT_PREFIX: '${{github.event.inputs.controller_id}}-solace-ci-controller'
  AZURE_RESOURCE_GROUP: '${{github.event.inputs.controller_id}}-solace-ci-controller-rg'
  AZURE_DEPLOY_ARM_TEMPLATE: ./azure/.workflows/azure-deploy.json
  BOOTSTRAP_SH: ./azure/.workflows/bootstrap.sh
  KEY_FILE: ./azure_key  
  PARAMTERS_TEMPLATE_FILE: ./azure/.workflows/template.azure-deploy.parameters.json
  PARAMETERS_FILE: ./azure/.workflows/azure-deploy.parameters.json
jobs:
  create_vm:
    runs-on: ubuntu-18.04
    outputs:
      publicIpAddress: ${{steps.azure_deploy.outputs.publicIPAddress}}
      resourceGroupName: ${{steps.azure_deploy.outputs.resourceGroupName}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      # - name: "TESTS: List Files after checkout"
      #   run: |
      #     pwd
      #     ls -a
      #     echo "GITHUB_SHA=$GITHUB_SHA"
      #     echo "GITHUB_REPOSITORY=$GITHUB_REPOSITORY"
      #     echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
      #     echo "GITHUB_REF=$GITHUB_REF"
      #     echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
      #     echo "github.token=${{ github.token }}"
      - name: Generate Parameters File
        run: |
          parametersJson=$(cat ${PARAMTERS_TEMPLATE_FILE} | jq .)
          echo parametersJson=$parametersJson
          export id=${{github.event.inputs.controller_id}}
            parametersJson=$( echo $parametersJson | jq -r '.parameters.id.value=env.id' )
          export zone=${{github.event.inputs.zone}}
            parametersJson=$( echo $parametersJson | jq -r '.parameters.zone.value=env.zone' )
          export vm_admin_username=${{github.event.inputs.vm_admin_username}}
            parametersJson=$( echo $parametersJson | jq -r '.parameters.vm_admin_username.value=env.vm_admin_username' )
          export vm_admin_public_key='
            {
              "reference": {
                "keyVault": {
                  "id": "/subscriptions/${{secrets.AZURE_SUBSCRIPTION_ID}}/resourceGroups/${{env.AZURE_RESOURCE_GROUP}}/providers/Microsoft.KeyVault/vaults/${{github.event.inputs.azure_key_vault_name}}"
                },
                "secretName": "${{github.event.inputs.vm_admin_public_key_secret_name}}"
              }
            }
            '  
            parametersJson=$( echo $parametersJson | jq -r '.parameters.vm_admin_public_key=(env.vm_admin_public_key|fromjson)' )

          echo $parametersJson | jq . > ${PARAMETERS_FILE}    

      # - name: Show Parameters File
      #   run: |
      #     cat ${PARAMETERS_FILE}

      - name: Generate Public/Private Key for Controller VM
        run: |
          ssh-keygen -t rsa -N '' -f ${KEY_FILE} <<< y 

      - name: Azure Login
        # https://github.com/marketplace/actions/azure-login
        uses: azure/login@v1.1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      # - name: "TEST: List all resource groups in specified location"
      #   run: |
      #     az group list --query "[?location=='${{github.event.inputs.azure_location}}']"

      - name: Create Azure Resource Group
        run: |
          az group create \
            --name ${AZURE_RESOURCE_GROUP} \
            --location ${{github.event.inputs.azure_location}} \
            --tags project=${PROJECT_PREFIX} \
            --verbose
      
      - name: Create Azure Key Vault
        run: |
          az keyvault create \
            --name ${{github.event.inputs.azure_key_vault_name}} \
            --resource-group ${AZURE_RESOURCE_GROUP} \
            --location ${{github.event.inputs.azure_location}} \
            --tags project=${PROJECT_PREFIX} \
            --enabled-for-template-deployment true \
            --verbose

      - name: Set Azure Key Vault Secret - vm public key
        run: |
          az keyvault secret set \
            --vault-name ${{github.event.inputs.azure_key_vault_name}} \
            --name ${{github.event.inputs.vm_admin_public_key_secret_name}} \
            --file ${KEY_FILE}.pub \
            --verbose
      
      - name: Set Azure Key Vault Secret - vm private key
        run: |
          az keyvault secret set \
            --vault-name ${{github.event.inputs.azure_key_vault_name}} \
            --name ${{github.event.inputs.vm_admin_private_key_secret_name}} \
            --file ${KEY_FILE} \
            --verbose

      - name: Run ARM Deploy
        id: azure_deploy
        # https://github.com/marketplace/actions/deploy-azure-resource-manager-arm-template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{env.AZURE_RESOURCE_GROUP}}
          template: ${{env.AZURE_DEPLOY_ARM_TEMPLATE}}
          # parameters: id=${{github.event.inputs.controller_id}} zone=${{github.event.inputs.zone}} vm_admin_username=${{github.event.inputs.vm_admin_username}} vm_admin_public_key=${{github.event.inputs.vm_admin_public_key}}
          # parameters: vm_admin_public_key=${{toJson(env.vmPublicKeyParam)}} id=${{github.event.inputs.controller_id}} zone=${{github.event.inputs.zone}} vm_admin_username=${{github.event.inputs.vm_admin_username}} 
          parameters: ${{env.PARAMETERS_FILE}}

      - name: "TEST: show the deploy output"
        run: |
          echo "outputs:"
          echo "${{toJson(steps.azure_deploy.outputs)}}"

      - name: Get the Private Key from Vault
        uses: Azure/get-keyvault-secrets@v1.0
        with:
          keyvault: ${{github.event.inputs.azure_key_vault_name}}
          secrets: '${{github.event.inputs.vm_admin_private_key_secret_name}}'  # comma separated list of secret keys that need to be fetched from the Key Vault 
        id: getVmAdminPrivateKey

      - name: Show Private Key
        run: |
          echo ${{steps.getVmAdminPrivateKey.outputs.vm_admin_private_key_secret_name}}    

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${SSH_KEY}" > ~/.ssh/controller.key
          chmod 600 ~/.ssh/controller.key
          cat >>~/.ssh/config <<END
          Host controller
            HostName ${SSH_HOST}
            User ${SSH_USER}
            IdentityFile ~/.ssh/controller.key
            StrictHostKeyChecking no
          END
          chmod 600 ~/.ssh/config
          
          cat ~/.ssh/config
          
        env:
          SSH_USER: ${{ github.event.inputs.vm_admin_username }}
          SSH_KEY: ${{ steps.getVmAdminPrivateKey.outputs.vm_admin_private_key_secret_name }}
          SSH_HOST: ${{ steps.azure_deploy.outputs.outputs.publicIpAddress }}

      - name: RUN ssh command
        run: |
          ssh controller "ls -la && pwd"
    
      - name: RUN ssh command
        run: |
          ssh controller "\
            ls -la && \
            pwd
          "

      - name: "DEBUG: STOP WORKFLOW"
        run: exit 1
      

  bootstrap_vm:
      runs-on: ubuntu-18.04
      needs: create_vm
      env:
        VM_PUBLIC_IP_ADDRESS: ${{needs.create_vm.outputs.publicIpAddress}}
        VM_USER_NAME: ${{github.event.inputs.vm_admin_username}}
        VM_PASSWORD: ${{github.event.inputs.vm_admin_password}}
      steps:
        - name: Checkout Repository
          uses: actions/checkout@master

        - name: Get the Private Key from Vault
          uses: Azure/get-keyvault-secrets@v1.0
          with:
            keyvault: ${{github.event.inputs.azure_key_vault_name}}
            secrets: '${{github.event.inputs.vm_admin_private_key_secret_name}}'  # comma separated list of secret keys that need to be fetched from the Key Vault 
          id: getVmAdminPrivateKey

        - name: Show Private Key
          run: |
            echo ${{steps.getVmAdminPrivateKey.outputs}}    

        - name: "DEBUG: STOP WORKFLOW"
          run: exit 1


         
        - name: "TEST: show the create_vm output"
          run: |
            echo "outputs from create_vm:"
            echo "publicIpAddress = ${VM_PUBLIC_IP_ADDRESS}"
            echo "resourceGroupName = ${{needs.create_vm.outputs.resourceGroupName}}"

        - name: Copy bootstrap script
          # https://github.com/garygrossgarten/github-action-scp
          # no error handling: workflow will not fail on error
          uses: garygrossgarten/github-action-scp@release
          with:
            local: ${{env.BOOTSTRAP_SH}}
            remote: bootstrap.sh
            host: ${{env.VM_PUBLIC_IP_ADDRESS}}
            username: ${{env.VM_USER_NAME}}
            password: ${{env.VM_PASSWORD}}
        - name: Execute bootstrap script
          # https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
          uses: garygrossgarten/github-action-ssh@release
          with:
            command: |
              chmod u+x bootstrap.sh
              ./bootstrap.sh
            host: ${{env.VM_PUBLIC_IP_ADDRESS}}
            username: ${{env.VM_USER_NAME}}
            password: ${{env.VM_PASSWORD}}


###
# The End.
