# ---------------------------------------------------------------------------------------------
# MIT License
# Copyright (c) 2020, Solace Corporation, Ricardo Gomez-Ulmke (ricardo.gomez-ulmke@solace.com)
# ---------------------------------------------------------------------------------------------

name: Test 2
on:
  workflow_run:
    workflows: ["Test 1"]
    types:
      - completed

env:
  ENV_T2_A: "ENV_T2_A"

jobs:
  run_test_1:
    runs-on: ubuntu-18.04

    steps:
      - name: Mock Run Test 1
        run: |
          echo "run test 1 here"
          echo "ENV_T1_A=$ENV_T1_A"


###
# The End.
